import { Task, Category } from "./types";

const today = new Date();
const fmt = (d: Date) => d.toISOString().split("T")[0];
const addDays = (d: Date, n: number) => {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r;
};

export const CATEGORIES: Category[] = [
  { id: "cat-1", name: "Kerja", color: "#9d27b0" },
  { id: "cat-2", name: "Pribadi", color: "#ff66cc" },
  { id: "cat-3", name: "Kesehatan", color: "#00c853" },
  { id: "cat-4", name: "Rapat", color: "#00c853" },
  { id: "cat-5", name: "Dev", color: "#9d27b0" },
];

export const DUMMY_TASKS: Task[] = [
  // Overdue
  {
    id: "t1",
    title: "Finalisasi Laporan Marketing Q3",
    description: "Selesaikan draft akhir dan kirim ke pemangku kepentingan.",
    date: fmt(addDays(today, -1)),
    startTime: "09:00",
    endTime: "10:00",
    isImportant: true,
    isUrgent: true,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-1"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t2",
    title: "Bayar tagihan listrik",
    description: "",
    date: fmt(addDays(today, -1)),
    startTime: "09:00",
    endTime: undefined,
    isImportant: false,
    isUrgent: true,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-2"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Today
  {
    id: "t3",
    title: "Rapat klien dengan tim desain",
    description: "Diskusikan redesain halaman landing baru.",
    date: fmt(today),
    startTime: "14:00",
    endTime: "15:00",
    isImportant: true,
    isUrgent: true,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-4"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t4",
    title: "Review pull request",
    description: "Cek PR #42, #43, #44.",
    date: fmt(today),
    startTime: "16:30",
    endTime: "17:00",
    isImportant: true,
    isUrgent: false,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-5"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t5",
    title: "Standup harian",
    description: "",
    date: fmt(today),
    startTime: "09:30",
    endTime: "09:45",
    isImportant: false,
    isUrgent: false,
    status: "completed",
    reminderSent: true,
    categoryIds: ["cat-4"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t6",
    title: "Perbaiki Masalah Database Produksi",
    description: "Kritis: connection pool habis di produksi.",
    date: fmt(today),
    startTime: "11:00",
    endTime: "12:00",
    isImportant: true,
    isUrgent: true,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-5"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Upcoming
  {
    id: "t7",
    title: "Siapkan slide presentasi",
    description: "Buat draft 10 slide awal untuk rapat review kuartalan.",
    date: fmt(addDays(today, 1)),
    startTime: "10:00",
    endTime: "12:00",
    isImportant: true,
    isUrgent: false,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-1"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t8",
    title: "Janji temu dokter gigi",
    description: "Klinik Dr. Smith, bawa kartu asuransi.",
    date: fmt(addDays(today, 2)),
    startTime: "14:00",
    endTime: "15:00",
    isImportant: false,
    isUrgent: false,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-2"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t9",
    title: "Belanja bahan makanan",
    description: "Susu, roti, telur, kopi.",
    date: fmt(addDays(today, 4)),
    isImportant: false,
    isUrgent: false,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-2"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Matrix extras
  {
    id: "t10",
    title: "Perencanaan Strategis 2024",
    description: "",
    date: fmt(addDays(today, 5)),
    isImportant: true,
    isUrgent: false,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-1"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t11",
    title: "Olahraga Gym (Hari Kaki)",
    description: "",
    date: fmt(addDays(today, 1)),
    startTime: "07:00",
    endTime: "08:00",
    isImportant: true,
    isUrgent: false,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-3"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t12",
    title: "Balas email vendor umum",
    description: "",
    date: fmt(today),
    isImportant: false,
    isUrgent: true,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-1"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t13",
    title: "Pesan tiket pesawat untuk konferensi",
    description: "",
    date: fmt(addDays(today, 3)),
    isImportant: false,
    isUrgent: true,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-1"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t14",
    title: "Scroll Media Sosial Tanpa Tujuan",
    description: "",
    date: fmt(today),
    isImportant: false,
    isUrgent: false,
    status: "completed",
    reminderSent: false,
    categoryIds: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t15",
    title: "Rapikan folder spam",
    description: "",
    date: fmt(today),
    isImportant: false,
    isUrgent: false,
    status: "completed",
    reminderSent: false,
    categoryIds: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t16",
    title: "Baca 'Deep Work'",
    description: "Bab 3 dan 4.",
    date: fmt(addDays(today, 6)),
    isImportant: true,
    isUrgent: false,
    status: "pending",
    reminderSent: false,
    categoryIds: ["cat-2"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
